### ISSUE TITLE
lack of expressions on "rythm games" dialogue

### ISSUE THREAD

**Issue by my-otter-self** [TheGamerSide67/MentalDisabilitySubmod#1]
hello. as you can check on [this](https://github.com/TheGamerSide67/MentalDisabilitySubmod/blob/main/MentalDisabilitiesTopics.rpy) file, the event labeled `mentalrhythmgames` has no expressions coded into it.

**Comment by TheGamerSide67** [comment]
This issue was resolved, thanks for letting me know!
